export interface CircuitData {
  fullName: string
  locality: string
  country: string
  length: string
  lengthKm: number
  laps: number
  lapRecord: string
  lapRecordHolder: string
  lapRecordYear: number
  drsZones: number
  corners: number
  direction: 'Clockwise' | 'Anti-clockwise'
  topSpeed: string
  downforceLevel: 'Very Low' | 'Low' | 'Medium' | 'High'
  circuitType: 'Permanent' | 'Street' | 'Semi-Permanent'
  firstGP: number
  character: string
}

export const CIRCUIT_DATA: Record<string, CircuitData> = {
  australia: {
    fullName: 'Albert Park Grand Prix Circuit',
    locality: 'Melbourne', country: 'Australia',
    length: '5.278 km', lengthKm: 5.278, laps: 58,
    lapRecord: '1:19.813', lapRecordHolder: 'Charles Leclerc', lapRecordYear: 2022,
    drsZones: 4, corners: 16, direction: 'Clockwise',
    topSpeed: '320 km/h', downforceLevel: 'Medium', circuitType: 'Street',
    firstGP: 1996,
    character: 'Semi-permanent street circuit around Albert Park lake. Fast flowing sections broken up by tight chicanes — sets the championship tone.',
  },
  china: {
    fullName: 'Shanghai International Circuit',
    locality: 'Shanghai', country: 'China',
    length: '5.451 km', lengthKm: 5.451, laps: 56,
    lapRecord: '1:32.238', lapRecordHolder: 'Michael Schumacher', lapRecordYear: 2004,
    drsZones: 2, corners: 16, direction: 'Clockwise',
    topSpeed: '330 km/h', downforceLevel: 'Medium', circuitType: 'Permanent',
    firstGP: 2004,
    character: 'Unique snail-shell layout with a near-180° hairpin entry. Demands strong traction on exit and rewards rear-stability through long radius sweepers.',
  },
  japan: {
    fullName: 'Suzuka International Racing Course',
    locality: 'Suzuka', country: 'Japan',
    length: '5.807 km', lengthKm: 5.807, laps: 53,
    lapRecord: '1:30.983', lapRecordHolder: 'Valtteri Bottas', lapRecordYear: 2019,
    drsZones: 1, corners: 18, direction: 'Clockwise',
    topSpeed: '315 km/h', downforceLevel: 'High', circuitType: 'Permanent',
    firstGP: 1987,
    character: 'The only figure-of-eight circuit on the calendar. Iconic 130R and the Esses demand extreme aero commitment — considered the ultimate driver\'s circuit.',
  },
  miami: {
    fullName: 'Miami International Autodrome',
    locality: 'Miami', country: 'United States',
    length: '5.412 km', lengthKm: 5.412, laps: 57,
    lapRecord: '1:29.708', lapRecordHolder: 'Max Verstappen', lapRecordYear: 2023,
    drsZones: 3, corners: 19, direction: 'Anti-clockwise',
    topSpeed: '320 km/h', downforceLevel: 'Medium', circuitType: 'Street',
    firstGP: 2022,
    character: 'Loops around Hard Rock Stadium. Three DRS zones and several hard braking points create genuine overtaking opportunities rarely seen at street circuits.',
  },
  canadian: {
    fullName: 'Circuit Gilles Villeneuve',
    locality: 'Montréal', country: 'Canada',
    length: '4.361 km', lengthKm: 4.361, laps: 70,
    lapRecord: '1:13.078', lapRecordHolder: 'Valtteri Bottas', lapRecordYear: 2019,
    drsZones: 2, corners: 14, direction: 'Clockwise',
    topSpeed: '340 km/h', downforceLevel: 'Low', circuitType: 'Semi-Permanent',
    firstGP: 1978,
    character: 'Classic power circuit on Île Notre-Dame. The Wall of Champions at the final chicane exit claims legends every year. Fuel saving and brake management are critical.',
  },
  monaco: {
    fullName: 'Circuit de Monaco',
    locality: 'Monte Carlo', country: 'Monaco',
    length: '3.337 km', lengthKm: 3.337, laps: 78,
    lapRecord: '1:12.909', lapRecordHolder: 'Lewis Hamilton', lapRecordYear: 2021,
    drsZones: 1, corners: 19, direction: 'Clockwise',
    topSpeed: '290 km/h', downforceLevel: 'High', circuitType: 'Street',
    firstGP: 1950,
    character: 'Shortest and slowest circuit on the calendar — the most demanding for precision. Qualifying position is almost everything; overtaking on track is nearly impossible.',
  },
  barcelona_catalunya: {
    fullName: 'Circuit de Barcelona-Catalunya',
    locality: 'Barcelona', country: 'Spain',
    length: '4.675 km', lengthKm: 4.675, laps: 66,
    lapRecord: '1:16.330', lapRecordHolder: 'Max Verstappen', lapRecordYear: 2023,
    drsZones: 2, corners: 16, direction: 'Clockwise',
    topSpeed: '330 km/h', downforceLevel: 'Medium', circuitType: 'Permanent',
    firstGP: 1991,
    character: 'The benchmark circuit — every team knows it inside out from pre-season testing. A well-balanced car wins here. Tyre degradation is severe through the long T3 right-hander.',
  },
  austrian: {
    fullName: 'Red Bull Ring',
    locality: 'Spielberg', country: 'Austria',
    length: '4.318 km', lengthKm: 4.318, laps: 71,
    lapRecord: '1:05.619', lapRecordHolder: 'Carlos Sainz', lapRecordYear: 2020,
    drsZones: 3, corners: 10, direction: 'Clockwise',
    topSpeed: '315 km/h', downforceLevel: 'Low',  circuitType: 'Permanent',
    firstGP: 1970,
    character: 'One of the shortest laps on the calendar. Dramatic elevation changes and just 10 corners — three long straights reward raw straight-line pace and strong ERS deployment.',
  },
  british: {
    fullName: 'Silverstone Circuit',
    locality: 'Silverstone', country: 'United Kingdom',
    length: '5.891 km', lengthKm: 5.891, laps: 52,
    lapRecord: '1:27.097', lapRecordHolder: 'Max Verstappen', lapRecordYear: 2020,
    drsZones: 2, corners: 18, direction: 'Clockwise',
    topSpeed: '310 km/h', downforceLevel: 'High', circuitType: 'Permanent',
    firstGP: 1950,
    character: 'Home of the world\'s first F1 race. Maggotts-Becketts-Chapel is the highest-speed corner complex in F1 — taken flat-out above 280 km/h in 2026-spec cars.',
  },
  belgian: {
    fullName: 'Circuit de Spa-Francorchamps',
    locality: 'Stavelot', country: 'Belgium',
    length: '7.004 km', lengthKm: 7.004, laps: 44,
    lapRecord: '1:46.286', lapRecordHolder: 'Valtteri Bottas', lapRecordYear: 2018,
    drsZones: 2, corners: 19, direction: 'Clockwise',
    topSpeed: '360 km/h', downforceLevel: 'Low', circuitType: 'Semi-Permanent',
    firstGP: 1950,
    character: 'The longest circuit on the calendar. Raidillon at the top of Eau Rouge is a defining F1 moment. Weather can change lap-by-lap — strategy calls are treacherous here.',
  },
  hungarian: {
    fullName: 'Hungaroring',
    locality: 'Budapest', country: 'Hungary',
    length: '4.381 km', lengthKm: 4.381, laps: 70,
    lapRecord: '1:16.627', lapRecordHolder: 'Lewis Hamilton', lapRecordYear: 2020,
    drsZones: 1, corners: 14, direction: 'Clockwise',
    topSpeed: '300 km/h', downforceLevel: 'High', circuitType: 'Permanent',
    firstGP: 1986,
    character: 'The Monaco of permanent circuits — tight, twisty, and nearly impossible to overtake. High-downforce setup, tyre management over long stints, and pit strategy decide outcomes.',
  },
  dutch: {
    fullName: 'Circuit Zandvoort',
    locality: 'Zandvoort', country: 'Netherlands',
    length: '4.259 km', lengthKm: 4.259, laps: 72,
    lapRecord: '1:11.097', lapRecordHolder: 'Lewis Hamilton', lapRecordYear: 2021,
    drsZones: 2, corners: 14, direction: 'Clockwise',
    topSpeed: '290 km/h', downforceLevel: 'High', circuitType: 'Permanent',
    firstGP: 1952,
    character: 'Banked corners — including 18-degree banking at Turn 3 — allow higher entry speeds and create unique mechanical loading. Coastal winds make car balance unpredictable.',
  },
  italian: {
    fullName: 'Autodromo Nazionale Monza',
    locality: 'Monza', country: 'Italy',
    length: '5.793 km', lengthKm: 5.793, laps: 53,
    lapRecord: '1:21.046', lapRecordHolder: 'Rubens Barrichello', lapRecordYear: 2004,
    drsZones: 2, corners: 11, direction: 'Clockwise',
    topSpeed: '375 km/h', downforceLevel: 'Very Low', circuitType: 'Permanent',
    firstGP: 1950,
    character: 'The Temple of Speed. Lowest downforce setting of the season — cars run almost flat wings. Slipstreaming into the first chicane defines both qualifying and race tactics.',
  },
  madrid: {
    fullName: 'Madrid Street Circuit',
    locality: 'Madrid', country: 'Spain',
    length: '5.500 km', lengthKm: 5.500, laps: 55,
    lapRecord: '—', lapRecordHolder: '—', lapRecordYear: 2026,
    drsZones: 3, corners: 20, direction: 'Anti-clockwise',
    topSpeed: '320 km/h', downforceLevel: 'Medium', circuitType: 'Street',
    firstGP: 2026,
    character: 'Brand-new street circuit through central Madrid. New for 2026 — no historical benchmarks. Early predictions suggest a power-sensitive layout with three good overtaking zones.',
  },
  azerbaijan: {
    fullName: 'Baku City Circuit',
    locality: 'Baku', country: 'Azerbaijan',
    length: '6.003 km', lengthKm: 6.003, laps: 51,
    lapRecord: '1:43.009', lapRecordHolder: 'Charles Leclerc', lapRecordYear: 2019,
    drsZones: 2, corners: 20, direction: 'Anti-clockwise',
    topSpeed: '370 km/h', downforceLevel: 'Low', circuitType: 'Street',
    firstGP: 2016,
    character: 'The longest straight in F1 at 2.2 km. The castle sector through the old city is barely two cars wide. Safety car deployments are almost guaranteed every year.',
  },
  singapore: {
    fullName: 'Marina Bay Street Circuit',
    locality: 'Singapore', country: 'Singapore',
    length: '4.940 km', lengthKm: 4.940, laps: 61,
    lapRecord: '1:35.867', lapRecordHolder: 'Kevin Magnussen', lapRecordYear: 2023,
    drsZones: 3, corners: 19, direction: 'Anti-clockwise',
    topSpeed: '295 km/h', downforceLevel: 'High', circuitType: 'Street',
    firstGP: 2008,
    character: 'F1\'s original night race. Extreme heat and humidity are as punishing as the circuit. Slow and technical — among the most physically draining for drivers all season.',
  },
  united_states: {
    fullName: 'Circuit of the Americas',
    locality: 'Austin', country: 'United States',
    length: '5.513 km', lengthKm: 5.513, laps: 56,
    lapRecord: '1:36.169', lapRecordHolder: 'Charles Leclerc', lapRecordYear: 2019,
    drsZones: 3, corners: 20, direction: 'Anti-clockwise',
    topSpeed: '335 km/h', downforceLevel: 'Medium', circuitType: 'Permanent',
    firstGP: 2012,
    character: 'Purpose-built to challenge every aspect of car design. Big elevation change at T1. Each sector references a different classic F1 circuit — Maggotts, Hockenheim, Hairpin.',
  },
  mexican_city: {
    fullName: 'Autodromo Hermanos Rodriguez',
    locality: 'Mexico City', country: 'Mexico',
    length: '4.304 km', lengthKm: 4.304, laps: 71,
    lapRecord: '1:17.774', lapRecordHolder: 'Valtteri Bottas', lapRecordYear: 2021,
    drsZones: 3, corners: 17, direction: 'Clockwise',
    topSpeed: '375 km/h', downforceLevel: 'High', circuitType: 'Permanent',
    firstGP: 1963,
    character: 'At 2,240 m altitude, thin air reduces downforce by ~20% and engine output by ~10%. Teams run extreme high-downforce to compensate — this paradox produces unique setups.',
  },
  sao_paulo: {
    fullName: 'Autodromo Jose Carlos Pace',
    locality: 'São Paulo', country: 'Brazil',
    length: '4.309 km', lengthKm: 4.309, laps: 71,
    lapRecord: '1:10.540', lapRecordHolder: 'Valtteri Bottas', lapRecordYear: 2018,
    drsZones: 2, corners: 15, direction: 'Anti-clockwise',
    topSpeed: '315 km/h', downforceLevel: 'Medium', circuitType: 'Permanent',
    firstGP: 1973,
    character: 'Undulating anti-clockwise layout with the famous Senna S-curve. Weather can swing from dry to torrential in minutes — the most unpredictable race of the year.',
  },
  las_vegas: {
    fullName: 'Las Vegas Strip Circuit',
    locality: 'Las Vegas', country: 'United States',
    length: '6.201 km', lengthKm: 6.201, laps: 50,
    lapRecord: '1:35.490', lapRecordHolder: 'Oscar Piastri', lapRecordYear: 2023,
    drsZones: 2, corners: 17, direction: 'Anti-clockwise',
    topSpeed: '350 km/h', downforceLevel: 'Low', circuitType: 'Street',
    firstGP: 2023,
    character: 'Night race down the iconic Strip. Three long straights produce the second-highest top speeds of the year. Cold overnight temperatures make tyre warm-up a critical challenge.',
  },
  qatar: {
    fullName: 'Losail International Circuit',
    locality: 'Lusail', country: 'Qatar',
    length: '5.380 km', lengthKm: 5.380, laps: 57,
    lapRecord: '1:24.319', lapRecordHolder: 'Max Verstappen', lapRecordYear: 2023,
    drsZones: 2, corners: 16, direction: 'Clockwise',
    topSpeed: '320 km/h', downforceLevel: 'High', circuitType: 'Permanent',
    firstGP: 2021,
    character: 'Fast and flowing under lights in the desert. The harshest circuit on tyres — multi-stop strategies are the norm. Rear-left degradation is the primary engineering challenge.',
  },
  abu_dhabi: {
    fullName: 'Yas Marina Circuit',
    locality: 'Abu Dhabi', country: 'UAE',
    length: '5.281 km', lengthKm: 5.281, laps: 58,
    lapRecord: '1:26.103', lapRecordHolder: 'Max Verstappen', lapRecordYear: 2021,
    drsZones: 2, corners: 16, direction: 'Anti-clockwise',
    topSpeed: '320 km/h', downforceLevel: 'Medium', circuitType: 'Permanent',
    firstGP: 2009,
    character: 'Season finale in the twilight. Completely redesigned in 2021 to allow more racing. Marina-side hotel section is distinctive — but the new layout transformed it from processional to genuinely competitive.',
  },
}
